/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package conectarproveedor;
import java.awt.event.KeyEvent;
import java.sql.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author david
 */
public class CapturadeMovimientos extends javax.swing.JFrame {

    /**
     * Creates new form CapturadeMovimientos
     */
    public CapturadeMovimientos() {
        initComponents();
    }

     public void mostrar(ResultSet consulta) throws SQLException {
        jTextFieldclave.setText(consulta.getString(1));
         jTextFielddescripcion.setText(consulta.getString(2));
            
        jTextFielddescripcion.setText(consulta.getString(3));           
             jTextFieldunidad.setText(consulta.getString(4));
             jTextFieldcantidad.setText(consulta.getString(5));
          jTextFieldprecio.setText(consulta.getString(6));
            jTextFieldtotal.setText(consulta.getString(7));
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnconsultar = new javax.swing.JButton();
        label1 = new java.awt.Label();
        jTextFieldnumero = new javax.swing.JTextField();
        jTextFieldclave = new javax.swing.JTextField();
        jbtnsiguiente = new javax.swing.JButton();
        jbtnultimo = new javax.swing.JButton();
        jTextFieldtotal = new javax.swing.JTextField();
        jTextFielddescripcion = new javax.swing.JTextField();
        jTextFieldunidad = new javax.swing.JTextField();
        jbtnmostrar = new javax.swing.JButton();
        jbtnprimero = new javax.swing.JButton();
        jbtnatras = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jbtnguardar = new javax.swing.JButton();
        button2 = new java.awt.Button();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        label7 = new java.awt.Label();
        jTextFieldcantidad = new javax.swing.JTextField();
        jTextFieldprecio = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbtnconsultar.setText("Limpiar");
        jbtnconsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnconsultarActionPerformed(evt);
            }
        });

        label1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label1.setText("Módulo de Captura de Productos");

        jbtnsiguiente.setText(">");
        jbtnsiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnsiguienteActionPerformed(evt);
            }
        });

        jbtnultimo.setText("->");
        jbtnultimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnultimoActionPerformed(evt);
            }
        });

        jTextFieldtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldtotalActionPerformed(evt);
            }
        });

        jbtnmostrar.setText("Mostrar");
        jbtnmostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnmostrarActionPerformed(evt);
            }
        });

        jbtnprimero.setText("<-");
        jbtnprimero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnprimeroActionPerformed(evt);
            }
        });

        jbtnatras.setText("<");
        jbtnatras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnatrasActionPerformed(evt);
            }
        });

        jButton1.setText("Eliminar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jbtnguardar.setIcon(new javax.swing.ImageIcon("D:\\iconos\\guardarnetbeans.ico")); // NOI18N
        jbtnguardar.setText("Guardar");
        jbtnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnguardarActionPerformed(evt);
            }
        });

        button2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        button2.setLabel("Cancelar");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel2.setText("Nímero de Movimiento:");

        label2.setText("Clave del Producto:");

        label3.setText("Descripción:");

        label4.setText("Unidad:");

        label5.setText("Cantidad:");

        label6.setText("Precio:");

        label7.setText("Total del Movimiento:");

        jTextFieldcantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldcantidadActionPerformed(evt);
            }
        });
        jTextFieldcantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldcantidadKeyTyped(evt);
            }
        });

        jTextFieldprecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldprecioKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(86, 86, 86)
                                        .addComponent(jbtnprimero))
                                    .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addComponent(jbtnatras)
                                        .addGap(58, 58, 58)
                                        .addComponent(jbtnsiguiente)
                                        .addGap(53, 53, 53)
                                        .addComponent(jbtnultimo)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFielddescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jTextFieldnumero, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextFieldclave, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jTextFieldcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(37, 37, 37)
                                                        .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(29, 29, 29)
                                                        .addComponent(jTextFieldprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(jTextFieldunidad, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextFieldtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton1)
                                        .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jbtnconsultar)
                                        .addComponent(jbtnmostrar))
                                    .addComponent(jbtnguardar, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtnguardar)
                                .addGap(35, 35, 35)
                                .addComponent(jbtnmostrar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(9, 9, 9)
                        .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnconsultar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(33, 33, 33)
                        .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldnumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldclave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFielddescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(jTextFieldunidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                                .addComponent(jTextFieldtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnprimero)
                            .addComponent(jbtnsiguiente)
                            .addComponent(jbtnatras)
                            .addComponent(jbtnultimo))
                        .addGap(51, 51, 51))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnconsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnconsultarActionPerformed
        //Boton Limpiar
        jTextFieldnumero.setText("");
        jTextFieldclave.setText("");
        jTextFielddescripcion.setText("");
        jTextFieldunidad.setText("");
        jTextFieldcantidad.setText("");
         jTextFieldprecio.setText("");
        jTextFieldtotal.setText("");


    }//GEN-LAST:event_jbtnconsultarActionPerformed

    private void jbtnsiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnsiguienteActionPerformed
        // Siguiente
        try {
            consulta.next();
            mostrar(consulta);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jbtnsiguienteActionPerformed

    private void jbtnultimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnultimoActionPerformed
        // Ultimo
        try {
            consulta.last();
            mostrar(consulta);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jbtnultimoActionPerformed

    private void jbtnmostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnmostrarActionPerformed
        try {
            conectar miconexion = new conectar();
            String cons = "select * from movimientos";
            consulta = miconexion.consulta(cons);
            consulta.next();
            mostrar(consulta);

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jbtnmostrarActionPerformed

    private void jbtnprimeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnprimeroActionPerformed
        try {
            consulta.first();
            mostrar(consulta);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jbtnprimeroActionPerformed

    private void jbtnatrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnatrasActionPerformed
        //Boton anterior
        try {
            consulta.previous();
            mostrar(consulta);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jbtnatrasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        /*
         * // Eliminar Registro//////////////////////////////////// { if (fila >
         * -1){ String codigo = String.valueOf(tabla.getValueAt(fila , 0));
         * p.deleteproducto(codigo); updateTabla(); fila=-1; }
    }
         
        String claveproducto;
        int p;
        limpiarTextos();
        claveproducto = JOptionPane.showInputDialog("Clave del producto a eliminar : ");
        Persona x = new Persona(claveproducto, "", "", "", 0, 0);
        p = LP.buscar(x);
        if (p != -1) {
            x = LP.getElemento(p);
            txtDni.setText(x.getDni());
            txtApellidos.setText(x.getApellidos());
            txtNombres.setText(x.getNombres());
            cboSexo.setSelectedItem(x.getSexo());
            txtEdad.setText(String.valueOf(x.getEdad()));
            txtPeso.setText(String.valueOf(x.getPeso()));
            int resp = JOptionPane.showConfirmDialog(this, "Deseas Eliminarlo ", "Eliminar Dato", JOptionPane.YES_NO_OPTION);
            if (resp == JOptionPane.YES_OPTION) {
                LP.eliminar(p);
                JOptionPane.showMessageDialog(this, "Registro eliminado");
            }
            limpiarTextos();
        } else {
            JOptionPane.showMessageDialog(null, "El dni de la persona no existe");
        }
*/
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbtnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnguardarActionPerformed

        try {
            //Instancias nuestra clase conectar
            conectar miconexion = new conectar();
            //Reemplaza valores 
            String sentenciaInsert = "insert into movimientos values (?,?,?,?,?,?,?)";
            miconexion.prepararSentencias = miconexion.miconexion.prepareStatement(sentenciaInsert);

            miconexion.prepararSentencias.setString(1, jTextFieldnumero.getText());
            miconexion.prepararSentencias.setString(2, jTextFieldclave.getText());
            miconexion.prepararSentencias.setString(3, jTextFielddescripcion.getText());           
            miconexion.prepararSentencias.setString(4, jTextFieldunidad.getText());
            miconexion.prepararSentencias.setString(5, jTextFieldcantidad.getText());
            miconexion.prepararSentencias.setString(6, jTextFieldprecio.getText());
            miconexion.prepararSentencias.setString(7, jTextFieldtotal.getText());

            miconexion.prepararSentencias.executeUpdate();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jbtnguardarActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_button2ActionPerformed

    private void jTextFieldcantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldcantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldcantidadActionPerformed

    private void jTextFieldtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldtotalActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextFieldtotalActionPerformed

    private void jTextFieldcantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldcantidadKeyTyped
  //////// Valida si es numero en el campor CANTIDAD/////////////////////////////
               
       int k=(int)evt.getKeyChar();
       if (k >= 97 && k <= 122 || k>=65 && k<=90){
       evt.setKeyChar((char)KeyEvent.VK_CLEAR);
       
       JOptionPane.showMessageDialog(null,"Caracter No valido","Ventana Error Datos",JOptionPane.ERROR_MESSAGE);
   }
       if(k==241 || k==209){
           
      evt.setKeyChar((char)KeyEvent.VK_CLEAR);
      JOptionPane.showMessageDialog(null,"Caracter No valido","Ventana Error Datos",JOptionPane.ERROR_MESSAGE);
}
if(k==10){
         jTextFieldcantidad.transferFocus();
}

    }//GEN-LAST:event_jTextFieldcantidadKeyTyped
////////////////////////////////////////////////////////////////////////////
    private void jTextFieldprecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldprecioKeyTyped
        // Valida si es numero en el campo PRECIO
        
        int k=(int)evt.getKeyChar();
       if (k >= 97 && k <= 122 || k>=65 && k<=90){
       evt.setKeyChar((char)KeyEvent.VK_CLEAR);
       
       JOptionPane.showMessageDialog(null,"Caracter No valido","Ventana Error Datos",JOptionPane.ERROR_MESSAGE);
   }
       if(k==241 || k==209){
           
      evt.setKeyChar((char)KeyEvent.VK_CLEAR);
      JOptionPane.showMessageDialog(null,"Caracter No valido","Ventana Error Datos",JOptionPane.ERROR_MESSAGE);
}
if(k==10){
         jTextFieldprecio.transferFocus();
        
    }//GEN-LAST:event_jTextFieldprecioKeyTyped
    }
    ////////////////////////////////////////////////////////////////////////////////////////////////
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CapturadeMovimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CapturadeMovimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CapturadeMovimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CapturadeMovimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new CapturadeMovimientos().setVisible(true);
            }
        });
    }
    ResultSet consulta;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldcantidad;
    private javax.swing.JTextField jTextFieldclave;
    private javax.swing.JTextField jTextFielddescripcion;
    private javax.swing.JTextField jTextFieldnumero;
    private javax.swing.JTextField jTextFieldprecio;
    private javax.swing.JTextField jTextFieldtotal;
    private javax.swing.JTextField jTextFieldunidad;
    private javax.swing.JButton jbtnatras;
    private javax.swing.JButton jbtnconsultar;
    private javax.swing.JButton jbtnguardar;
    private javax.swing.JButton jbtnmostrar;
    private javax.swing.JButton jbtnprimero;
    private javax.swing.JButton jbtnsiguiente;
    private javax.swing.JButton jbtnultimo;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    // End of variables declaration//GEN-END:variables
}
